config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
	resources :posts
	
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, presence: true
  validates :cost, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  belongs_to :user

  geocoded_by :address
  after_validation :geocode
 
  def self.search(search)
  	if search
  		search.downcase! # same as search = search.downcase
  		where("lower(title) LIKE ?", "%#{search}%")
  	else
  		all
  	end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # make sure user is logged in before viewing site
  before_action :authenticate_user! 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.search(params[:search])
  end

  def new
    @post = Post.new
    @title = 'Create a new post'
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post.id) # /posts/:id
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id]) # pulls id from /posts/:id in url
  end

  def edit
    @post = Post.find(params[:id])
    if current_user == @post.user
      render :edit
    else
      flash[:alert] = "Access denied!"
      redirect_to root_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if current_user == @post.user && @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
    else
      flash[:alert] = "Access denied!"
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :cost, :body, :image, :longitude, :latitude, :address, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" id="<%= current_page?(new_post_path) ? 'new-post-header' : 'sitewide-header' %>">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Craigslist Clone</h1>
          <hr class="small">
          <span class="subheading"><%= @title || 'Welcome to our couch app!' %></span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <%= link_to 'Craigslist Clone', root_path, class: 'navbar-brand', id: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to 'New Post', new_post_path %></li>
        <!-- Search form -->
        <%= form_tag posts_path, :method => 'get', class: 'navbar-form navbar-left' do %>
        <div class='form-group col-xs-12 floating-label-form-group controls'>
          <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search' %>
        </div>
        <%= submit_tag "Search", :name => nil, id: 'btn-navbar-search', tabindex: '-1' %>
        <% end %>
        <!-- /search form -->
        <% if user_signed_in? %>
        <li><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraigslistClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript"
         src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['maps_api_key'] %>">
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/header' %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@post.errors.count, "error") %> prohibited
			this post from being saved:
		</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<%= f.input :title %>
	<%= f.input :cost %>
	<%= f.input :body %>
	<%= f.input :image, as: :file %>
	<%= f.input :address %>

	<%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>Posts</h1>
	</div>
	<% @posts.each do |post| %>
	<div class="col-md-3">
		<div class="thumbnail">
			<%= link_to post do %>
				<%= image_tag post.image, class: 'post-images' %>
			<% end %>
			<p>
				<strong><%= link_to post.title, post %></strong>
			</p>
			<p><%= number_to_currency(post.cost) %></p>
		</div>
	</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-4">
		<div class="thumbnail">
			<%= image_tag @post.image %>
		</div>
	</div>
	<div class="col-md-8">
		<p>Post creator: <%= @post.user.email %></p>
		<h1><%= @post.title %></h1>
		<p><%= number_to_currency @post.cost %></p>
		<p><%= @post.body %></p>
		<% if current_user == @post.user %>
		<p><%= link_to 'Edit', edit_post_path(@post.id)%> | <%= link_to 'Delete', post_path(@post.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
		<% end %>
	</div>
	<div class="col-md-12">
		<h3>Location: <%= @post.address %></h3>
		<div id="map-container">
		  <div id="map-canvas"></div>
		</div>
	</div>
</div>

<%= javascript_tag do %>
	latitude = '<%= j @post.latitude.to_s %>';
	longitude = '<%= j @post.longitude.to_s %>';
	title = '<%= j @post.title %>';
	cost = '<%= j number_to_currency(@post.cost) %>';
	address = '<%= j @post.address %>';
<% end %>